---
services:
  php:
    platform: linux/x86_64
    env_file: App/.env
    build:
      args:
        GID: ${GID:-1000}
        UID: ${UID:-1000}
      context: App
    volumes:
      - "./App:/usr/src/app"
    restart: unless-stopped

  nginx:
    build: services/nginx
    ports:
      - 80:80
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./App/public:/usr/src/app/public
    restart: unless-stopped

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  adminer:
    image: adminer:4.8.1
    ports: [8080:8080]

volumes:
  database_data:
