---
services:
  php:
    image: leogrouet/qui-paie-quoi:php-${VERSION_NAME}
    platform: linux/x86_64
    env_file: App/.env
    build:
      args:
        GID: ${GID:-1000}
        UID: ${UID:-1000}
      context: App
    restart: unless-stopped

  nginx:
    image: leogrouet/qui-paie-quoi:nginx-${VERSION_NAME}
    build:
      context: .
      target: prod
      dockerfile: services/nginx/Dockerfile
    ports:
      - 80:80
    restart: unless-stopped

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  adminer:
    image: adminer:4.8.1
    ports: [8080:8080]

volumes:
  database_data:
