parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Command\HandleBalanceCommand: ~
  App\Command\DatabaseFlushTest: ~
  
  App\Controller\GroupController: ~
  App\Controller\RegisterController: ~

  App\Repository\ExpenseRepository: ~
  App\Repository\GroupRepository: ~
  App\Repository\UserRepository: ~

  App\Form\:
    resource: '%kernel.project_dir%/src/Form'

  App\Service\GroupExpenseBalancer: ~

  App\Twig\FormatNumber:
    tags: ['twig.extension']