parameters:
  env(DATABASE_HOST): "database"
  env(DATABASE_PORT): "5432"
  env(DATABASE_NAME): "app"
  env(DATABASE_VERSION): "16.4"


services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Command\HandleBalanceCommand: ~
  App\Command\DatabaseFlushTest: ~
  
  App\Controller\:
    resource: '%kernel.project_dir%/src/Controller/**/*Controller.php'
    tags: ['controller.service_arguments']

  App\Repository\ExpenseRepository: ~
  App\Repository\GroupRepository: ~
  App\Repository\UserRepository: ~
  App\Repository\UserBalanceRepository: ~

  App\Form\:
    resource: '%kernel.project_dir%/src/Form'

  App\Service\ExpenseBalancer: ~

  App\Twig\FormatNumber:
    tags: ['twig.extension']