parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Command\HandleBalanceCommand: ~
  App\Command\DatabaseFlushTest: ~

  App\Repository\ExpenseRepository: ~
  App\Repository\GroupRepository: ~
  App\Repository\UserRepository: ~
  App\Service\GroupExpenseBalancer: ~

  App\Controller\GroupController: ~
  App\Tests: ~

  App\Twig\FormatNumber:
    tags: ['twig.extension']
