parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Command\HandleBalanceCommand: ~
  App\Repository\ExpenseRepository: ~
  App\Repository\GroupRepository: ~
  App\Service\GroupExpenseBalancer: ~
  App\Controller\GroupController: ~
