security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            form_login:
                login_path: signin
                check_path: signin
                default_target_path: groups_home
                enable_csrf: true
            logout:
                path: /logout
                target: signin
    access_control:
         - { path: '^/groups', roles: ROLE_USER }
when@test:
    security:
        password_hashers:
          
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
