name: "CI"

on: [push]

concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ["ubuntu-latest"]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies handler
        run : |
          echo GID=$(id -g) > .env
          echo UID=$UID >> .env
          cp App/.env.dist App/.env

      - name: Build Docker PHP Image
        run : docker compose build php

      - name: Composer Install
        run : make composer-install  

      - name: Run php-cs-fixer
        run : make phpcsfixer-dev

      - name: Run php Analytics
        run : make phpstan

      - name: Run phpunit
        run : make phpunit
      
      - name: Run Behat
        run : make behat-test
  