name: "CI"

on: [commit]

concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

jobs:
  csfixer:
    runs-on: ["ubuntu-latest"]

    steps:
        uses: actions/checkout@v4
      - run : make phpstan
      - run : make phpcsfixer