name: "CI"

on: [push]

concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ["ubuntu-latest"]

    steps:
      - uses: actions/checkout@v4
      - run : docker build
      - run : composer install
      - run : docker compose up
      - run : make phpstan
      - run : make phpcsfixer-dev